### ISSUE TITLE
Changing build plate temperature is not recognized as customized setting

### ISSUE THREAD

**Issue by kgms2** [5axes/CuraSettingsWriter#11]
If I change the built plate temperature from its default, e.g. 85°C, to 60°C, CuraSettingsWriter does not recognize that this setting differs from the default. Therefore I cannot use the option to only show the values that are not default.

Please find an example html-file attached.
[test60.html.txt](https://github.com/5axes/CuraSettingsWriter/files/7257834/test60.html.txt)

**Comment by 5axes** [comment]
Hello I'm not sure to really understand your remark . 
Default built plate temperature  and built plate temperature  are two different settings.  and the option to display values which are different from the default in this case default mean different form the initial profile value, so changed by the user.

**Comment by kgms2** [comment]
Hi 5axes,

maybe I understood the Interface wrong. I thought, if I click on "custom selection", all unchanged settings would be hidden. Which would be very handy, because this way it would be possible to see at the first look, what I changed.

My problem now is, that I changed a setting (Build plate temparature), but this setting is also hidden, if I click "custom selection", although it has a different value compared to the initial value in the profile.

As you can see, in Cura there is this backwards rotating arrow, indicating that I made a change. But the setting has no green background in the html-file which would indicate the same.
![2021-09-30_13-44](https://user-images.githubusercontent.com/91657308/135450225-5e10e7ce-7d36-400e-a809-52ec9715d18d.png)

![2021-09-30_13-54](https://user-images.githubusercontent.com/91657308/135450576-915645ce-e1b6-47c3-a452-b25238757a97.png)

**Comment by 5axes** [comment]
ok it's clear now

**Comment by 5axes** [comment]
Note for me : 
Modifications of these datas are considered as a Machine level user modification and not a top of stack modification.  That's why they are not listed as a modified user parameter. Looks like possible also to test this level , something to do in a futur release.
![image](https://user-images.githubusercontent.com/11015345/167090968-3c6f7b9e-9bfc-4edc-a0b3-a6d5031c8589.png)

**Comment by 5axes** [comment]
Should be fixed in V2.1.2
