### ISSUE TITLE
"Experimental" settings category for each extruder in case of multi-extruder printer (Cura 4.8.0)

### ISSUE THREAD

**Issue by Unipto** [5axes/CuraSettingsWriter#15]
Hello,

I am working with a 4 extruder 3D printer and Cura 4.8.0. When I save my project in HTML format, there is only one category for "Experimental" settings, as if those settings were all common to all extruders, which is not the case. I saw that this issue has been fixed for other versions of Cura. 
I actually fixed the issue myself locally, just by moving and slightly modifying 1 line of the plugin code: 
- Move line 204 "self._doTree(extruders[0],"experimental",stream,0,0)" in the for loop around line 190.
- Change the line to "self._doTree(Extrud,"experimental",stream,0,i)".

As I am working on Cura on multiple computers, I would prefer no having to make this change on each computer. Could you please make this change for Cura 4.8.0 ?

**Comment by 5axes** [comment]
This Issue is already fixed,

If you use the last release : https://github.com/5axes/CuraSettingsWriter/releases/tag/V2.0.0  It should be OK

**Comment by Unipto** [comment]
Indeed my bad !
Sorry for the inconvenience and thank you for your quick answer.
