### ISSUE TITLE
Plugin loads but not visible in File menu

### ISSUE THREAD

**Issue by wademaxfield** [5axes/CuraSettingsWriter#16]
MacOS 13.5 / Cura 5.3 & 5.4
Plugin version 2.1.1 from marketplace, or 2.1.3 from github.

Plugin is listed as loading in the cura.log, and no errors are listed.

```2023-08-20 16:27:30,101 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin HTMLCuraSettings 2.1.3```

I have tried disabling all other plugins but that does not make any difference.

[cura.log](https://github.com/5axes/CuraSettingsWriter/files/12387317/cura.log)

I've read the other issues here, and know you do not have a Mac to try this on, but is there anything I can try or look for to help diagnose this?

**Comment by 5axes** [comment]
Sorry I don't see any informations in your log file to help you.

**Comment by wademaxfield** [comment]
Is there anywhere else to look for info? A way to turn on extra debugging?    I read elsewhere that some plugins can fail to be visible based on their naming:  https://community.ultimaker.com/topic/31085-settings-guide-plugin-not-showing/

I'm not a python programmer, but I've tried renaming the plugin files and the class name to HtmlCuraInfo to see if that might be involved - I got to the point of no Cura throwing no errors, and showing the renamed plugin as loaded (in the log) but it still didn't appear in the File menu.  Is there a way to get the plugin to appear in Extensions menu rather than File menu?

**Comment by 5axes** [comment]
Sometimes a plugin can be installed but not activated in Cura . Did you check that ?

![image](https://github.com/5axes/CuraSettingsWriter/assets/11015345/427a01f2-2614-4b4f-ac73-114bee159f57)

**Comment by wademaxfield** [comment]
Yes.
<img width="858" alt="Screenshot 2023-08-21 at 23 01 35" src="https://github.com/5axes/CuraSettingsWriter/assets/1421049/2e23f75f-83db-42b4-b7a9-876ad91df637">

I've also tried logging into my Mac using the Guest user account (to simulate a clean cura install), and only installing this plugin.

**Comment by wademaxfield** [comment]
Please accept my apologies.  I have figured out what I have been missing.  I have been looking for an item that I thought was going to be appended to the File menu after Save Project.

It actually adds a new file output option/format in the Save File dialog when you select File > Save Project.
