### ISSUE TITLE
Add options to import settings.

### ISSUE THREAD

**Issue by mirspan** [5axes/CuraSettingsWriter#18]
Add options to import saved settings.

**Comment by 5axes** [comment]
There is an option to import the savefile.

**Comment by the-moog** [comment]
Though a CSV file is not very structured.  A bit '90s.  How about using one or more of XML, TOML, Python Pickles, YAML, JSON....
Then add a git repo so that we can track changes and merge properties.
We could even auto tag the repo for each print, so we never lose that perfect tweek.

**Comment by 5axes** [comment]
Nice idea, loves to use your plugin.
