### ISSUE TITLE
Plugin not showing up on a mac in Cura 4.6.2

### ISSUE THREAD

**Issue by Albercook** [5axes/CuraSettingsWriter#4]
According to the marketplace tab it is installed. I tried restarting cura. I'm not sure where the file is supposed to be but I looked in contents>resources>plugins it does not appear to be there.

I thought that it might have installed in an older version but it doesn't appear to have and the marketplace tab says it should be there.

Other plugins, which appear under extensions, are working.

**Comment by Albercook** [comment]
Just downloaded the latest version of Cura. Still not seeing the option.

**Comment by 5axes** [comment]
Sorry I'm not a mac user, I cannot help you on this point

**Comment by 5axes** [comment]
Try with the last release : https://github.com/5axes/CuraSettingsWriter/releases/tag/1.0.6  but not very sure the success

**Comment by 5axes** [comment]
2020  --- No answer can close this issue
