### ISSUE TITLE
Idea Automatic generation with exporting the G-code

### ISSUE THREAD

**Issue by qalsalaa** [5axes/CuraSettingsWriter#5]
would maybe be agood idea to Export the Settings while we expor the Gcode automaticcly? will that be hard to programm?

**Comment by 5axes** [comment]
Hello, Thank for your idea. I don't know if it's very hard but it's strangely not so obvious. The other problem is that the generation of a document file multiplies the files and that saving them directly on sd card is not necessarily the right place to store them.  For that needs I prefer to use the solution to use a postprocessing string as I already do and save with the Gcode the main settings. You will find a sample scripts here : [https://github.com/5axes/Cura-Postprocessing-Scripts/blob/master/GCodeDocumentation.py](https://github.com/5axes/Cura-Postprocessing-Scripts/blob/master/GCodeDocumentation.py)

**Comment by qalsalaa** [comment]
Hallo, thanks very much for your Support!
one Question, is there the Possibility to run Gcode every 10 Layer 
![image](https://user-images.githubusercontent.com/54896065/102088918-d72cab00-3e1b-11eb-9e63-67de44fd12ac.png)
for Example here so the Idea is to clean the Nozzle every X-Layer in this Example 10-Layer

so the Printer will move every 10-Layer to this Position for Example:
![image](https://user-images.githubusercontent.com/54896065/102089113-12c77500-3e1c-11eb-852d-6c93c3f04964.png)
this position is where we have a Brush to clean the Nozzle.

would that be Possible? or could you maybe tell me how could i do something like that!
i'm new in Programming and have no Experience!

Thank you very much

**Comment by 5axes** [comment]
yes it's possible : https://github.com/5axes/Cura-Postprocessing-Scripts/blob/master/InsertAtLayerChange.py
![Insert](https://user-images.githubusercontent.com/11015345/102093134-19a4b680-3e21-11eb-81a3-28d6385b8760.JPG)

**Comment by qalsalaa** [comment]
Thanks for your quick answer, i appreciate that!  when i add the code it shown like this in the Textedirot:
![image](https://user-images.githubusercontent.com/54896065/102096743-55417f80-3e25-11eb-9e1c-dcce38894c3e.png)

and you know more than one G-comand on one line will not be work, like in this case it will only run G0 X-80 Y330 Z10

it have to be like this way to run the hole G-code
G0 X-80 Y330 Z10
G0 X-80 Y300  Z10
G0 X-80 Y330 Z10 
there is any Command, G-code to write the G-code Vertical?

**Comment by 5axes** [comment]
Use the new version and add **<br>** between each line . I don't know why but **\n** doesn't work

**Comment by qalsalaa** [comment]
thanks alot, but where i have to add it? in the G-code it did'nt worked!

or you mean  somewhere inside this ?
![image](https://user-images.githubusercontent.com/54896065/102216078-ec1c4380-3eda-11eb-9dde-1b44b3aabdac.png)

**Comment by 5axes** [comment]
G0 X-80 Y330 Z10<br>G0 X-80 Y300 Z10

**Comment by qalsalaa** [comment]
thanks alot for Support, i have on Question, i want to print some Settings in Gcode like at the first of the Gcode, and after that export that Settings as Excel everything working fine.
i insert like this:
```
; acceleration_enabled = {acceleration_enabled}
; acceleration_infill = {acceleration_infill}
; acceleration_ironing = {acceleration_ironing}
```
and after that read the Gcode as txt file and at the End to Excel .......
**My Questions is ** how can i print the Support Material and Print Material, Bounding Box too, i could not find the Reference for that, do you have maybe Table or something like that from where you read your Settings=?

**Comment by 5axes** [comment]
Hello,

These informations are not avalaible via a parameter, You must develloped a plugin or a postprocesing script to get these data. A good start for the code is the SliceInfoPlugin [https://github.com/Ultimaker/Cura/tree/master/plugins/SliceInfoPlugin](https://github.com/Ultimaker/Cura/tree/master/plugins/SliceInfoPlugin)

**Comment by 5axes** [comment]
Can close now this Issue : New plugin https://github.com/5axes/CuraHtmlDoc

To generate the HTML file each time you Generate the G-Code
