### ISSUE TITLE
Intent profile not written to html

### ISSUE THREAD

**Issue by nallath** [5axes/CuraSettingsWriter#7]
A number of machines (most notably the Ultimaker S5 & S3) have an extra layer of profiles, the so called "Intent" profiles.

The selection made there is not reflected in the stored HTML file.

**Comment by 5axes** [comment]
Ok need to test it ..

**Comment by 5axes** [comment]
not so easy .. how to get the Name of the profil ?  
Engineering Normal :
![image](https://user-images.githubusercontent.com/11015345/111979194-0fbbdf00-8b05-11eb-8991-dde5644fbf40.png)
if in fact the profile **Accurate** ?
![image](https://user-images.githubusercontent.com/11015345/111979156-0599e080-8b05-11eb-85c8-4c4ee974f178.png)

**Comment by nallath** [comment]
Hmm, I have no idea why we have the name like that. I've looked through the actual code and it seems that we simply translate the intent_category (and not the name)

**Comment by 5axes** [comment]
ok need to get in this case the **intent_category** 
![image](https://user-images.githubusercontent.com/11015345/112003517-4142a380-8b21-11eb-88f0-2bf5eb01fced.png)

**Comment by 5axes** [comment]
ok got it !
![image](https://user-images.githubusercontent.com/11015345/112011309-6f77b180-8b28-11eb-8a3c-a48c5cd635c3.png)
`
        # Profile || Intent for Ultimaker Machine
        P_Name = global_stack.qualityChanges.getMetaData().get("name", "")
        if P_Name=="empty":
            P_Name = machine_manager.activeIntentCategory
            self._WriteTd(stream,i18n_cura_catalog.i18nc("@label","Intent"),P_Name)
        else:
            self._WriteTd(stream,i18n_cura_catalog.i18nc("@label","Profile"),P_Name)
`

**Comment by 5axes** [comment]
Solved V1.1.1
